name: Freetify
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, github actions"
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
        with: 
          path: our-source
      - run: ls -al our-source
      - run: cat our-source/.github/workflows/main.yml
